### ISSUE TITLE
in certain colorschemes you cant see the cursor

### ISSUE THREAD

**Issue by angelidis** [mangelozzi/rgflow.nvim#9] opened 2023-12-10 20:14 UTC
thanks for developing this, it's an amazing plugin!

i noticed that in some colorschemes you can't see the cursor on the 3 lines (Flags, Pattern, Path).

is there something i can do on the user side, so i can see the cursor?

example colorcheme:     'navarasu/onedark.nvim' (the "warm" style and light background)

**Comment by mangelozzi** [comment] 2023-12-19 13:32
Thanks for finding the issue! I installed one dark theme and set it to `warm`, this is what looks like for me (I tried to screen shot but the cursor turned to an outline during the brief moment the screen shot tool takes focus, so heres a GIF instead):
![cursor](https://github.com/mangelozzi/rgflow.nvim/assets/19764314/ae7839c5-29ed-4b06-b03e-f51a6b3cd586)

Would you please post a screen shot of how it looks to help us try figure out what the issue is?

**Comment by mangelozzi** [comment] 2024-01-04 13:13
Are you using Windows Terminal by any change? That has an option for set high contrast, which can adjust the cursor when it sees fit.
Please let me know what OS and shell you are using, cheers!

**Comment by mangelozzi** [comment] 2024-01-05 08:18
Feel free to open this issue again if you can provide a way to recreate it, cheers!

**Comment by xixiaofinland** [comment] 2024-01-05 09:21
@mangelozzi  I can reproduce it
try this popular theme rebelot/kanagawa.nvim
it gives a grey-white background and the cursor is hard to detect

![Screenshot 2024-01-05 at 11 20 39](https://github.com/mangelozzi/rgflow.nvim/assets/13655323/493f4029-4fb7-4524-abef-af4a724c132b)

**Comment by towry** [comment] 2024-01-06 00:04
```
  opts = {
    default_trigger_mappings = false,
    default_ui_mappings = true,
    default_quickfix_mappings = true,
    -- you can override it with vim.b.grep_flags
    cmd_flags = '--smart-case --fixed-strings --no-fixed-strings -M 500',
    colors = {
      RgFlowInputPath = { link = 'NormalFloat' },
      RgFlowInputBg = { link = 'NormalFloat' },
      RgFlowInputFlags = { link = 'NormalFloat' },
      RgFlowInputPattern = { link = 'NormalFloat' },
    },
  },
```

**Comment by angelidis** [comment] 2024-01-06 11:52
(happy new year!) and apologies for the delayed reply, just saw this:

here is a screenshot:

![image](https://github.com/mangelozzi/rgflow.nvim/assets/1413007/430280ab-c982-46ee-8175-fcaff9433a79)

this happens with multiple themes, when using neovide.

if i use the same theme in terminal nvim, you can barely see the cursor.
(windows, wez terminal, neovide, nvim-0.9.4)

**Comment by angelidis** [comment] 2024-01-06 11:56
> ```
>   opts = {
>     default_trigger_mappings = false,
>     default_ui_mappings = true,
>     default_quickfix_mappings = true,
>     -- you can override it with vim.b.grep_flags
>     cmd_flags = '--smart-case --fixed-strings --no-fixed-strings -M 500',
>     colors = {
>       RgFlowInputPath = { link = 'NormalFloat' },
>       RgFlowInputBg = { link = 'NormalFloat' },
>       RgFlowInputFlags = { link = 'NormalFloat' },
>       RgFlowInputPattern = { link = 'NormalFloat' },
>     },
>   },
> ```

this works!
(if anyone can explain this, it would be very much appreciated!)

**Comment by towry** [comment] 2024-01-06 17:51
This is rgflow's option to allow you changing the highlight of rgflow ui. IMO you can close this, unless this issue bother other people and this option doesn't meet their needs.

**Comment by angelidis** [comment] 2024-01-07 09:18
appreciate the explanation towry (and the help!)

i misspoke in my original comment -- meant to say, how come this isn't taken care of with the application of a colorscheme?

the really high model of colorschemes i have in my mind, is that you define groups, and they provide colors.
so if this is a correct model, how come the cursor color was off while using rgflow but not off while using other plugins?

(not sure if my question makes sense -- just curious at this point, problem was solved)

**Comment by mangelozzi** [comment] 2024-01-10 11:40
Hi All, Thanks @towry and @xixiaofinland for the help.

I still can't reproduce the issue, this is what I see with `colorscheme kanagawa-wave`:
![image](https://github.com/mangelozzi/rgflow.nvim/assets/19764314/e74cd2f3-a6f6-4094-a4bb-cb38a6b75de3)

But it seems like @towry is onto a good thing with linking to `NormalFloat`. I will look into.

**Comment by mangelozzi** [comment] 2024-01-11 12:22
Okay pushed a fix, I used to do all sorts of color math and tricks to calculate the colorscheme on fly, but now I just keep it simple and link to existing highlight theme groups. I also updated the readme to link to @towry's work. 
@angelidis feel free to try it now and see it works for you.

Cheers!

**Comment by angelidis** [comment] 2024-01-14 16:19
it seems like now it's working great!
thanks again for everything!

**Closed** 2024-01-15 11:03 UTC
