### ISSUE TITLE
Column number is not correct

### ISSUE THREAD

**Issue by doongjohn** [mangelozzi/rgflow.nvim#4] opened 2023-10-02 23:22 UTC
![image](https://github.com/mangelozzi/rgflow.nvim/assets/40219740/33c92dcf-8d42-4e16-b5d3-16b914b910c9)

Column number is not correct if there are multiple matches in a single line.

**Comment by mangelozzi** [comment] 2023-10-20 09:40
> Thank you for fixing this isssue 😄 However did you push your commits? Latest commit is last week.

Sorry my bad, the push failed cause I hadnt pulled in a PR and I didnt notice. Okay now its really released!

**Comment by doongjohn** [comment] 2023-10-20 11:44
hmm it errors when I press enter and it does not add anything to the quickfix list
```
Error executing vim.schedule lua callback: ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:24: Index out of bounds
stack traceback:
        [C]: in function 'nvim_buf_get_lines'
        ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:24: in function 'get_qf_buffer_lines'
        ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:89: in function 'set_and_apply_pattern_highlights'
        ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:264: in function <...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:223>
```

**Comment by mangelozzi** [comment] 2023-10-20 12:46
> hmm it errors when I press enter and it does not add anything to the quickfix list
> 
> ```
> Error executing vim.schedule lua callback: ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:24: Index out of bounds
> stack traceback:
>         [C]: in function 'nvim_buf_get_lines'
>         ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:24: in function 'get_qf_buffer_lines'
>         ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:89: in function 'set_and_apply_pattern_highlights'
>         ...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:264: in function <...Local/nvim-data/lazy/rgflow.nvim/lua/rgflow/quickfix.lua:223>
> ```

Can't reproduce it, but I am on Linux, are you perhaps using Windows? I ask that cause I did change the way the ripgrep output is buffered/pieced together. I suspect it might be a CRLF vs LF issue if you are on windows. I only have access to windows PC when I am back at work on Monday.

**Comment by doongjohn** [comment] 2023-10-20 13:05
Yes I'm on windows.

**Comment by doongjohn** [comment] 2023-10-20 13:09
After the update it does not output error but the quickfix list is empty

**Comment by mangelozzi** [comment] 2023-10-21 06:17
> After the update it does not output error but the quickfix list is empty

Oh goodness, PS yesterday I did another release that continues on a highlight error, but did not mention it cause I was hoping to do a better release, you can update for now if you wish but I'm still working on it. Thanks for your patience!

**Comment by mangelozzi** [comment] 2023-10-24 18:26
Tested on windows, and its fixed now! Thanks for holding tight. Windows with their extra colons in filenames was the issue! Something as silly as that, cheers mate!

**Comment by doongjohn** [comment] 2023-10-24 19:59
Thanks! It's fixed for me too👍

**Comment by mangelozzi** [comment] 2023-10-25 06:12
Thanks again for reporting this one, happy vim'ming!

**Closed by mangelozzi** 2023-10-25 06:12 UTC
